config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'
  resources:articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    flash[:success]="Article has been created"
    redirect_to articles_path

  end

  private
  def article_params
    params.require(:article).permit(:title,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Create a new article</h1>
<%=link_to "New Article",new_article_path %>

app/views/articles/new.html.erb
<h3 class='text-center'> Adding New Article</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :title %>
</div>
<div class='col-md-11'>
<%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :body %>
</div>
<div class='col-md-11'>
<%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
</div>
</div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
      </button>
    <%=link_to "Blog App",root_path,class: "navbar-brand"%>

 </div>
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="activ"><%= link_to "Authors","#" %></li>
      </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}"%>'>
      <a href='#' class='close' data-dismiss='alert' &#215;></a>
      <%= content_tag :div, msg, :id =>"flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="col-md-8">
          <%= yield %>
      </div>
        <div class="col-md-4">
          <%= yield :sidebar %>
      </div>
     </div>
    </div>
   </div>

</body>
</html>